// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_FLFASDjKMBoGlvy4OsPB8u5UqsvoIw',
    appId: '1:805459774198:android:5d8ec4ccd6527849533ad7',
    messagingSenderId: '805459774198',
    projectId: 'bioquiet',
    databaseURL: 'https://bioquiet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bioquiet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5HcS-rAqzIwElO86mT8C9_Di2SOLBLI',
    appId: '1:805459774198:ios:82fb3b9a310a5e5d533ad7',
    messagingSenderId: '805459774198',
    projectId: 'bioquiet',
    databaseURL: 'https://bioquiet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bioquiet.firebasestorage.app',
    iosClientId: '805459774198-l2kgphqs1lvnr1vv96a8hh5nu9qskd1g.apps.googleusercontent.com',
    iosBundleId: 'es.upm.etsisi.mad.bioquietcross.bioquietCross',
  );
}
